# Generated by Django 2.2.1 on 2019-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
