# Generated by Django 2.2.1 on 2019-06-01 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0002_auto_20190601_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wannablab.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language', to='wannablab.Language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_member', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
