# Generated by Django 2.2.1 on 2019-06-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0003_auto_20190601_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_language', to='wannablab.Language'),
        ),
    ]
