# Generated by Django 2.2.1 on 2019-06-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0004_auto_20190601_2331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
