# Generated by Django 2.2.1 on 2019-06-14 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wannablab', '0006_auto_20190603_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='member',
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='event_member', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
