# Generated by Django 2.2.1 on 2019-06-21 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0007_auto_20190614_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(null=True, related_name='event_member', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
