# Generated by Django 2.2.1 on 2019-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0009_auto_20190621_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default='A1', max_length=2, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Language level',
                'verbose_name_plural': 'Language levels',
                'db_table': 'level',
            },
        ),
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
    ]
