# Generated by Django 2.2.1 on 2019-07-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0011_auto_20190723_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default='A1', max_length=2, verbose_name='Name'),
        ),
    ]
