# Generated by Django 2.2.1 on 2019-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0012_auto_20190723_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
