# Generated by Django 2.2.1 on 2019-07-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0016_auto_20190723_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_level', to='wannablab.Level'),
        ),
    ]
