# Generated by Django 2.2.1 on 2019-07-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wannablab', '0017_event_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='shot_name',
            new_name='name',
        ),
    ]
