# Generated by Django 2.2.1 on 2019-06-01 20:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wannablab', '0004_auto_20190601_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Image')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('info', models.TextField(verbose_name='Info about user')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_language', to='wannablab.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
            },
        ),
    ]
